### PR TITLE
New css tags

### LINKED ISSUE #6: User can create/assign tags on post

### LINKED ISSUE #14: Search for posts with tags

### LINKED ISSUE #16: Bug: Extra space on top when tag addition is canceled

### LINKED ISSUE #28: CSS tags
this is unrelated to the other css request

### LINKED ISSUE #36: Making the CSS work nicely when resizing window
Issue Description:
When the tags list is big, this makes the post div too big and causes the posts to squish when resizing the website horizontally.

Potential Solution:
- Make the tags div a fixed width
- Make the tags into a flexbox to wrap each tag (might want to center the flexbox too)
- Make the tags wrap around if there are too many so the post div is sized appropriately

### LINKED ISSUE #37: Tag Selector: add visuals to show that a tag is selected
Issue Description:
When you click on a tag in the dropdown tag selector at the top of the website, the tag does not have an indicator that signifies the tag has been selected.

Potential Solutions:
- Change the background of the tag when the button is clicked.

### PR DESCRIPTION
**Pull request by MauricioESerrano**
Closes #37 
Closes #36 
Closes #14 
Closes #28 
Closes #16 
Closes #6 

Resolves #37 
Resolves #36 
Resolves #14 
Resolves #28 
Resolves #16 
Resolves #6

### CODE REVIEW

**Review by derryl0925 — APPROVED** [review]
reveiw

**Comment by derryl0925** [comment]
Just fixed validation issues, next time please make sure everything works before requesting to merge

**Review by 4hlecks — APPROVED** [review]
looks good

**Review by Augustus31 — APPROVED** [review]
perhaps a bit too much for one merge, but we were rushed on the last day :/

overall excellent work, thank you to everyone who helped!

**Pull request merged**
