### PR TITLE
E2E Git Actions now functional

### PR DESCRIPTION
**Pull request by Augustus31**
Merge ASAP, before feature merges

### CODE REVIEW

**Review by MauricioESerrano — APPROVED** [review]

**Review by Waterblokey — APPROVED** [review]
Thanks Dev

**Review by derryl0925 — APPROVED** [review]
looks good and all but 1 test seem to pass

**Review by Waterblokey — APPROVED** [review]
Great work!

**Review by MauricioESerrano — APPROVED** [review]

**Review by wishful-0405 — APPROVED** [review]
Looks Good

**Comment by jtung0705** [comment]
looks good

**Pull request closed without merging**
